# Generated by Django 3.1.1 on 2020-09-29 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20200929_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCommant',
            new_name='BlogComment',
        ),
    ]
